dim_edge_vert: 4
dim_edge_hori: 4
dim_features: 6
N_train: 100
N_valid: 100
N_test: 100
degree: 5
additive_noise: 1.0
scale_noise_uni: 1.0
scale_noise_div: 1.0
attack_threshold: 1.0
attack_power: 1.0
name: temp_data