name: sp
dim_edge_vert: 4
dim_edge_hori: 4
dim_features: 6
N_train: 100
N_valid: 100
N_test: 100
degree: 4
additive_noise: 0.0
scale_noise_uni: 0.0
scale_noise_div: 0.0
attack_threshold: 0.0
attack_power: 0.0
